spring:
 datasource:
  url: "jdbc:h2:mem:testdb"
  driver-class: "org.h2.Driver"
  username: "sa"
  password: ""
 jpa:
  properties:
   hibernate:
    dialect: "org.hibernate.dialect.H2Dialect" 
  hibernate:
   ddl-auto: update
   show-sql: true
server:
 port: 8089
logging:
 level:
  org:
   springframework:
    jdbc:
     datasource:
      init:
       ScriptUtils: debug
